# Preprocessing: Water treatment plants

**Objective**: Prepare data from the **MERKUR** dataset for use in machine learning algorithms.

**Background**: The MERKUR project, based in the *Research Centre for Built Environment, Climate, Water Technology and Digitalisation* at VIA University College, collects and analyzes data from water treatment plants in Denmark. In short, the project aims to understand how water treatment plants are run, and the results are then ideally used to optimize the running of water treatment plants. However, the dataset is, as of now, relatively "dirty" in a machine learning context: There are many missing values, outliers, a mix of categorical and numeric data, etc.

**Data Source**: The dataset has kindly been provided to us by Senior Associate Professor Loren Mark Ramsay. You can read more [here](https://en.via.dk/research/built-environment-climate-water-technology-and-digitalisation/water-treatment-and-distribution) and [here](https://www.ucviden.dk/en/projects/merkur-national-web-baseret-dataplatform-til-drikkevandsbehandlin).

Note that we are only working with a subset of the full database. This subset is saved as an Excel file, `merkur.xlsx`.

#### Overall Instructions
1. Explore the dataset to understand the features and their distributions.
2. Preprocess the data, handling any missing values, outliers, etc.

Below some suggestions are given but the assignment is relatively "free".

Best of luck with your analysis!

### Suggestions

-  Filter out (i.e. remove) any irrelevant columns (e.g. names, IDs, etc.)
-  Several columns contain missing values (NaNs). Find out how large a percentage each column is missing. Perhaps some of them lack so much data that you should consider removing them?
-  Scale numeric data.
-  For the features you choose to keep, impute the missing values in an appropriate way - or perhaps you find it more appropriate to delete the rows?
-  Several features (e.g., "PrimaryTrigger") are categorical. Use one-hot encoding to turn them into numeric data. Be careful with the feature "Stages" - perhaps one-hot encoding is not the best choice here?
-  If you you choose to remove or replace outliers, do this now. If you choose to keep, move on.
-  Create a correlation matrix and discuss - based on this, you might want to drop certain columns.
-  Consider whether some features should be transformed (e.g. using log, square root etc.) and do this if found relevant.
-  There are only about 80 rows in the data set. Discuss consequences of this in terms of machine learning - as well as potential solutions. 
-  Think about whether there are other steps you find appropriate at this point. If not, declare your data set clean.

In [13]:
import pandas as pd
df = pd.read_excel(r"merkur.xlsx")
df

,WaterworksName,TotalFilters,MaxTypicalFlow,AverageFilterArea,AverageTypicalRunVolume,AverageBackwashVolume,PrimaryTrigger,AverageTotalFilterDepth,OverallFilterGrainSizeMin,OverallFilterGrainSizeMax,...,SumOfld_layer,UniformityCoefficient,UFRV,BW%,HLR_BW,TankCapacity,TankExploitation,GravityPressureMixed,Stages,AbstractedVolume
0,Asnæs Vandværk,6,50.00,6.000000,5200.00000,10.00,Time,NaN,NaN,NaN,...,NaN,NaN,866.666667,0.414525,NaN,27.294778,NaN,Gravity,Single,253543
1,Assens Vandværk,4,110.00,4.908739,300.00000,28.00,Volume,310.0,0.8,5.0,...,2891.666665,NaN,40.743665,23.000062,30.557749,2.576075,NaN,Pressure,Double,612094
2,Astrup Vandværk - Esbjerg,4,120.00,15.343900,3800.00000,83.30,Volume,190.0,2.0,35.0,...,759.000000,1.491,249.217919,2.192086,32.791831,21.825600,NaN,Gravity,Double,682318
3,Astrup Vandværk - Skjern,2,NaN,16.000000,1200.00000,26.00,Volume,NaN,NaN,NaN,...,NaN,NaN,75.000000,2.166907,NaN,12.554300,NaN,Gravity,Single,156998
4,Avernakø Vandværk,2,NaN,1.495000,250.00000,4.50,Volume,NaN,1.6,32.0,...,NaN,NaN,167.224093,1.818182,NaN,52.220566,NaN,Gravity,Single,6710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Værket ved Regnemark,16,1426.00,47.940002,NaN,110.00,Mix,142.0,0.8,150.0,...,90.809524,NaN,NaN,0.178441,NaN,9.176959,39.682540,Gravity,Double,11454775
75,Værket ved Søndersø,20,1407.29,10.178760,4500.00000,57.00,Volume,190.0,0.8,8.0,...,1708.095230,1.625,442.097088,1.236822,51.086775,6.040393,NaN,Pressure,Single,11021800
76,Østerbyværket,6,250.00,14.752500,2331.50137,51.57,Time,170.0,1.4,4.0,...,842.857154,1.850,158.041107,4.446077,30.367735,22.367525,45.833333,Gravity,Single,423362
77,Østre Vandværk - Herning,12,NaN,37.437401,4400.00000,134.00,Volume,NaN,NaN,NaN,...,NaN,NaN,93.489396,35.386015,32.053507,NaN,NaN,Gravity,Double,1521895
78,Østrup Skov Vandværk,5,329.92,17.000000,2684.00000,45.00,Time,NaN,NaN,NaN,...,NaN,NaN,157.882353,1.647232,NaN,NaN,36.345136,Gravity,Single,712225

In [14]:
df.dtypes
df.describe()

,TotalFilters,MaxTypicalFlow,AverageFilterArea,AverageTypicalRunVolume,AverageBackwashVolume,AverageTotalFilterDepth,OverallFilterGrainSizeMin,OverallFilterGrainSizeMax,AverageFilterBedVolume,FilterExploitation,...,TotalEBCT,Footprint,SumOfld_layer,UniformityCoefficient,UFRV,BW%,HLR_BW,TankCapacity,TankExploitation,AbstractedVolume
count,79.000000,63.000000,75.000000,77.000000,69.000000,46.000000,45.000000,45.000000,45.000000,63.000000,...,40.000000,75.000000,40.000000,28.000000,72.000000,66.000000,52.000000,75.000000,49.000000,7.900000e+01
mean,6.253165,218.548317,11.701130,5084.251052,39.444947,149.741718,1.182889,24.597778,18.201472,60.364608,...,39.814000,77.606708,933.232182,2.553929,312.084063,2.958973,31.658679,18.293085,24.396803,1.098328e+06
std,4.046107,276.007063,8.713576,8915.477406,35.830905,60.124935,0.607748,27.950415,11.662481,23.630246,...,28.006186,74.700616,691.185500,3.976901,205.220383,5.505880,11.599788,14.290136,18.823818,1.854600e+06
min,1.000000,6.500000,1.327323,250.000000,0.800000,80.000000,0.500000,1.400000,1.725520,15.335576,...,4.890000,8.352477,90.809524,1.372000,40.743665,0.073715,0.469337,2.576075,2.459016,6.710000e+03
25%,3.000000,61.665000,4.908739,1500.000000,15.000000,101.000000,0.800000,5.000000,9.290160,40.881888,...,21.932500,30.610861,479.003472,1.469750,166.430789,0.999476,28.112067,8.697479,10.394265,2.427655e+05
50%,5.000000,120.000000,10.178760,3250.000000,30.000000,139.000000,1.000000,9.000000,18.000000,63.279585,...,32.440000,59.830096,842.857154,1.639000,258.637091,1.525787,30.889453,15.097670,19.402985,5.980330e+05
75%,8.000000,257.650000,14.986250,5000.000000,50.000000,173.750000,1.400000,35.000000,22.508998,78.567831,...,47.232500,94.377094,1090.541768,2.063500,433.805656,2.260182,35.800161,23.851035,35.714286,1.216296e+06
max,20.000000,1426.000000,47.940002,63000.000000,169.550000,310.000000,4.000000,150.000000,60.686602,117.396568,...,154.180000,448.614229,2891.666665,22.690000,1130.094353,35.386015,68.022071,96.433289,86.013986,1.145478e+07

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# 1. Load and Initial Exploration
df = pd.read_excel("merkur.xlsx")

# 2. Create a copy for preprocessing
df_clean = df.copy()

# 3. Separate features by type
numeric_features = df_clean.select_dtypes(include=['float64', 'int64']).columns
categorical_features = df_clean.select_dtypes(include=['object']).columns

# Remove WaterworksName as it's just an identifier
df_clean = df_clean.drop('WaterworksName', axis=1)

# 4. Analyze missing values
missing_percentages = (df_clean.isnull().sum() / len(df_clean)) * 100
print("Missing values percentage per column:")
print(missing_percentages)

# 5. Remove columns with too many missing values (>50%)
columns_to_drop = missing_percentages[missing_percentages > 50].index
df_clean = df_clean.drop(columns_to_drop, axis=1)

In [4]:

# 6. Create preprocessing pipelines
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(drop='first'))
])

In [5]:
# 7. Special handling for 'Stages' column
# Convert to ordinal encoding since it has natural ordering
stages_mapping = {'Single': 1, 'Double': 2}
df_clean['Stages'] = df_clean['Stages'].map(stages_mapping)

In [6]:
# 8. Create preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, [col for col in numeric_features if col != 'Stages']),
        ('cat', categorical_transformer, [col for col in categorical_features if col != 'Stages'])
    ])

In [ ]:
# 9. Fit and transform the data
X_processed = preprocessor.fit_transform(df_clean)

In [ ]:




# 10. Create correlation matrix visualization
plt.figure(figsize=(15, 10))
correlation_matrix = pd.DataFrame(X_processed).corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Matrix of Processed Features')
plt.tight_layout()
plt.show()

# 11. Detect and handle outliers
def detect_outliers(df, columns):
    outliers_dict = {}
    for column in columns:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        outliers = df[(df[column] < (Q1 - 1.5 * IQR)) | (df[column] > (Q3 + 1.5 * IQR))][column]
        if len(outliers) > 0:
            outliers_dict[column] = len(outliers)
    return outliers_dict

# Detect outliers in numeric columns
outliers = detect_outliers(df_clean, numeric_features)
print("\nNumber of outliers per column:")
print(outliers)

# 12. Save processed dataset
processed_df = pd.DataFrame(X_processed)
processed_df.to_csv('processed_merkur_data.csv', index=False)

# 13. Print summary statistics
print("\nSummary of preprocessing:")
print(f"Original shape: {df.shape}")
print(f"Processed shape: {X_processed.shape}")
print(f"Number of features removed due to missing values: {len(columns_to_drop)}")
print(f"Number of numeric features: {len(numeric_features)}")
print(f"Number of categorical features: {len(categorical_features)}")

# 14. Additional visualizations
plt.figure(figsize=(15, 5))
plt.subplot(1, 2, 1)
plt.title('Distribution of Stages')
df_clean['Stages'].hist()
plt.xlabel('Stages (1=Single, 2=Double)')

plt.subplot(1, 2, 2)
plt.title('Distribution of AbstractedVolume')
plt.hist(df_clean['AbstractedVolume'], bins=30)
plt.xlabel('AbstractedVolume')
plt.tight_layout()
plt.show()